### ISSUE TITLE
[QUESTION]How to load the driver?

### ISSUE THREAD

**Issue by hAbd0u** [namazso/hdd_serial_spoofer#3]
Hello,
I managed to compile the driver successfuly with Visual studio 2019, there are some files, mainly `hwid.sys` and `WdfCoinstaller01009.dll`, now how to load this driver?

**Comment by namazso** [comment]
enable test mode, create a service of type kernel with path to driver, then start it

or use OSRLOADER

or [TDL](https://github.com/hfiref0x/TDL) for loading without disabling test mode. 

anyways, this repo is primarily for developers and others who know what they're doing

**Comment by hAbd0u** [comment]
Thanks for this replay, now it loaded but the hard disk is not changed.
Test environment:
Win 10 x64 Build 17763.
![image](https://user-images.githubusercontent.com/6846543/78297177-5ba9f880-752f-11ea-9145-e42eace24f61.png)

**Comment by namazso** [comment]
a bit late but for future reference: wmi caches serial numbers, therefore it will show the old one if you query like this.
