### ISSUE TITLE
I want to change the serial number in real time, without rebooting the computer ,is that possible ?

### ISSUE THREAD

**Issue by iouvxz** [namazso/hdd_serial_spoofer#4]
What documentation should I read to accomplish this function ?

**Comment by namazso** [comment]
none, should work normally

**Comment by iouvxz** [comment]
> none, should work normally

Sorry ,I'm a noob .

Does that mean it's already implemented somewhere in the source code or do I have to reboot it every time when I want to change my serial number ?

**Comment by namazso** [comment]
no, you just don't need to read any documentation because it is obvious how to implement if you read the code. simply change the seed and that's all.

**Comment by iouvxz** [comment]
> no, you just don't need to read any documentation because it is obvious how to implement if you read the code. simply change the seed and that's all.

I see ,I just figured it out and want to delete my reply .
**spoof_serial** is called each time when I query the serial number ,
I just need to manually control what **spoof_serial** writes to memory ,that's all .
